deploy:
  provider: pypi
  user: geislor
  password:
    secure: d1ka0AdiRi/HuXPRtWBtL/GCffn5Xj7XSvpzbQorHdeGQtjtdYld76K1l/J6f4URiTg1VNQo7VY5E2DRNARcZh+VVRqzHOiVYBX5KtOG9Bc7fVjqStsaNRld1N0M3nsomKHOld4LZt1Wn2w6kKXmH8XjQqt+dvHJLrcV9iUjZvR1U0X2VTTrrRbzx7K1dktB/atL4CgS19aC9E5X7EPpiGrtn7WiCJv7Agw/7lTUKUwchWuDxf8JrZ9gEpfIFehrIGmRgUlrU00JLvJJ1NvgH35RwKtCSMEnyL+6kxD7sh1DR2MkxHPsJnbQDgzHWMEcqGZaBym5040b5Gvnz/MVAR+bS2S069xoXO/+m94LBOIonqJEBw+78LDwa7Hql5l0WH4w3ex5G0dKslL53xpI4c8QbUIl3JlGdfrkxSE7T9yt0jTo1DmMRE+i9FRYyrS3IQG2vFCeShYXvKm3lahlfiSIXBRYVN3jlBvJy5yGkJvB25DKs9DiHrDT6utdt2brSduc6DG70Ae5loco9mhxX105p37eBMuY9pDyCinaizl8l3QPGRIsWISq5QLMCI+yJZGDmu6Ba8Opo2B3NVQGi7/PvuhO2igHSZcUcrANz52Z3rSwA8dQRNA5IOBGEpH9NWeQgr/xghjEI3/sgnbb+CWI2+s6l1/2/puujMZ6xRM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: geislor/apus
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=py26
install: pip install -U tox sqlalchemy
language: python
python: 3.5
script: tox -e ${TOXENV}
notifications:
  email:
    recipients:
    - geislor@gmail.com
  slack: antlia:yi0MtfE2vi8JWOlH20w7SN61
