deploy:
  on:
    condition: "$TOXENV == py27"
    repo: geislor/apus
    tags: true
  provider: pypi
  password:
    secure: g5cl5snbm/FzQ+UwVlESpboDJuWDXQ3Ceu7a+UWJu4MUSlqAula+ZRwupHabVxAZ3mrBNvxBjvqJ4p7LAsEilrZ2Kwb7ea/4Ndx1atm24uYwwPYEI/nF+nGbaGBDUR6lB9vIs7q06sNe3Q3I1VIWxceqX6VS+BCYCj/6f14BinoDtgqyFZ00a7ah+b/wvduSV0GY/xZ+6tuGEpe+m1hQxn4VQQRN5ej9NmaYM1j1JTOhfTATmSbqcDcx+yqwRiKX8FKOmYj2YbPqFozb8OPv38rhUTciDeV5PxAtJtc90ROBqwNz8waGv/afsJ7Jk0V0PfKvwxXFES72ZK4sNxB/u8mP/CYUWoqnSTn9aWtl8IlRLUJTnzmYFvCJ+eJ6Hdy67+OIuxO/VdBl+6J1fElkGoBePcEe1udTo7nm6rdqRC8Y/a83zU7EH/L+bMPE2jNzZWQ4Hsw+nW0zusSaVdngRYUBf00XK/TZmUiAcDit+mJ0WK0tI3x1lIJAsWuCaiuAneZ6S8U/MmL+hxWoS/at8RMUQ/6LYrfPxWGEPAP91CJB1plBzZXKgZwcUPtBmWabiikL4W6sl652nPpvaYRG3VPdFjiGCYcnMMDOTXaJiBg2VhpC3Jd47i1c4HEQIcuwczOCOc5tyZfmtbgUimDGyDB0tUgKmSsdrBbAwYFbZVw=
  user: geislor
  distributions: sdist bdist_wheel
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=py26
install: pip install -U tox sqlalchemy
language: python
python: 3.5
script: tox -e ${TOXENV}
notifications:
  email:
    recipients:
    - geislor@gmail.com
  slack: antlia:yi0MtfE2vi8JWOlH20w7SN61
